### ISSUE TITLE
Getting Error after adding mutiple drive id

### ISSUE THREAD

**Issue by vishansh** [SVR666/search-bot#1]
I added mutiple drive id from different teamdrive it's giving error file not found in logger

**Comment by SVR666** [comment]
i don't have any problem.

**Comment by vishansh** [comment]
Weird it's working now can u tell how to display teamdrive names instead of number 1,2,3 what to edit

**Comment by SVR666** [comment]
> Weird it's working now can u tell how to display teamdrive names instead of number 1,2,3 what to edit

check new update
